url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Yanok AI | AI PaaS" # the name of your site, e.g. ACME Corp.


plugins:
  - jekyll-inline-svg
  - jekyll-postcss
  - jekyll-redirect-from
  - jekyll-sitemap

postcss:
  cache: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - node_modules/
  - .bundle_cache
