# change the followings to match your Github username and repo name
baseurl: "/"
url: "https://www.yanok.ai.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Yanok"
description: Yanok AI

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: false
footer-msg-link: fasle

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
